template_path: templates/dynamodb-lab.py
sceptre_user_data:
  HashKeyElementName: testHash
  HashKeyElementType: S
  ReadCapacityUnits: 5
  WriteCapacityUnits: 5
  queue: test-queue
  lambda_db_entry_to_sqs: 
    MemorySize: 128
    Timeout: 60